version: '3'
services:
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - 9432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: consentimientos_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xpoldyht
  web:
    build: .
    command: bundle exec rails s -p 3500 -b '0.0.0.0'
    volumes:
      - .:/usr/src/consentimientos
    ports:
      - "3500:3000"
    depends_on:
      - db
